name: Deploy Hybrid Connectivity

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-hybrid-connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Hybrid Connectivity
        uses: azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            Set-AzContext -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

            ./automation/create-hybridconnectivity.ps1 `
              -ResourceGroupName "rg-core-dev-weu" `
              -VirtualNetworkName "vnet-core-dev-weu" `
              -GatewaySubnetAddressPrefix "10.10.255.0/27" `
              -PublicIpName "pip-vpngw-core-dev-weu" `
              -Location "westeurope" `
              -RootCertificatePath "./certs/cloud-org-infra-root-cert.cer"
